---
title: "Produktområde Arbeidsgiver"
execute:
    echo: false
    warning: false
format:
    dashboard:
        embed-resources: true
        nav-buttons:
            - icon: github
              href: https://github.com/navikt/arbeidsgiver-datafortelling
            - icon: slack
              href: https://nav-it.slack.com/archives/CCM649PDH
jupyter: python3
---

# Operative mål 2024

## Row
~~Arbeidsgivere får tak i relevant arbeidskraft når de kontakter NAV for rekruttering og inkludering.~~

Første halvår: Vurdere behov for videre utvikling av verktøy som kan tiretellege for god og effektiv match mellom prioriterte brukergrupper og arbeidsgivere, og samtidig ivaretar personvernet.

## Row
Arbeidsgivere opplever en mer koordinert og relevant NAV i samhandling om skaffe arbeid, beholde arbeid og omstilling.

## Row
Vi bruker et språk på nav.no/arbeidsgiver som arbeidsgivere forstår og har en struktur som gjør det enkelt for arbeidsgivere å finne det de leter etter.

## Row
Vi skal gjøre det lettere for NAV-ansatte å kartlegge arbeidsgivers behov, og evaluere den tidsbegrensende og målrettede innsatsen.

# Toi

## Row
**Mål for første halvår 2024:** Vurdere behov for videre utvikling av verktøy som kan tiretellege for god og effektiv match mellom prioriterte brukergrupper og arbeidsgivere, og samtidig ivaretar personvernet.

- K1: Bidra til å lukke og håndtere oppfølging av personvernbruddet i Rekrutteringsbistand.
- K2: Sikre at løsningen for Rekrutteringsbistand ivaretar krav til sikkerhet og personvern.
- K3: Vurdere videre utvikling av Rekrutteringsbistand i tett samarbeid med team Arbeidsmarked og Markedskontoret.

## Row
**Mål 2. tertial:**

- Sikre en trygg og stabil løsning.
- Skal ha implementert ny rollebasert tilgangsstyring, både roller og geografi. 
- Implementere tiltak fra ROSer og ny PVK. Ajour med etterlevelse. 
- Ha sammensmeltet og forankret prioriteringer. 

Key results:

- K1: Helsemetrikk på antall personer i prioritert målgruppe blir formidlet (litt lagging)
- K2: Helsemetrikk på antall personer i prioritert målgruppe får åpnet sin kontaktinformasjon av arbeidsgivere  (leading indikator)
- K3: Vi har implementert ny rollebasert tilgangsstyring, både roller + begrensning i hvilke CV-er rollene har tilgang til (basert på hvor kandidaten har sitt NAV-kontor tilknytning (i Modia)). 
- K4: Har impementert tiltak i ROSer og PVKer. 
- K5: Har en omforent og forankret prioriteringsliste sammen med de sammensmeltede team Arbeidsmarked og Markedskontoret. 

# Salesforce

## Row
**Mål 2024:** Arbeidsgivere opplever en mer koordinert og relevant NAV i samhandling om skaffe arbeid, beholde arbeid og omstilling

- K1: Implementere dialogløsningen til alle NAV kontor (forutsatt at dialogløsningen som har vært i pilot besluttes å tas i bruk).
- K2: Mer loggføring og oppdatering av dialog og samhandling med arbeidsgivere skal øke med 20 % målt mot samme periode i forrige år.
- K3: Øke andelen av NAV-ansatte som svarer at de har oversikt over arbeidsgivere som kan inkludere fra prioriterte mål grupper i vår årlige undersøkelse, fra 75% til 80%.
- K4: Lage kontrollpanel med oversikt over aktiviteter og status på IA saker for alle 12 fylker.
- K5: Øke andelen aktive IA saker som har regsitrerte aktiviteter pr måned fra 10 % til 15 %.

## Row

**Mål 1. tertial:** NAV-ansatte skal få en bedre oversikt over aktiviteter, også fra andre fagsystemer, knyttet til den enkelte arbeidsgiver i Salesforce. Slik at de får færre arbeidsflater å forholde seg til, og vi motiverer til økt bruk av løsningen.

- K1: Øke antall loggføring og aktiviteter på arbeidsgiverkontakt med 5 % sammenlignet med samme periode forrige år.
- K2: Vise oppgaver fra andre fagsystemer i Salesforce.

## Row

**Mål 2. tertial:** Utarbeide beslutningsgrunnlag for nasjonal utrulling av dialogløsning.

- K1: Etterlevelse av sikkerhetskrav til dialogløsningen slik at dialogløsningen kan anbefales for videre utrulling.
- K2: Øke antall dialogmeldinger med 200%.
- K3: 8 av 10 som har prøvd dialogløsningen ønsker å beholde den.

# Innholdstrion

## Row

**Mål 2024:** Vi bruker et språk på nav.no/arbeidsgiver som arbeidsgivere forstår og har en struktur som gjør det enkelt for arbeidsgiverne å finne det de leter etter.

- K1: Tiden arbeidsgiver legger på nødvendige NAV-oppgaver reduseres, og de føler seg trygge på at de har gjort det de skal.
- K2: Av arbeidsgivere som blir dultet til inkludering og forebygging av sykefravær, foretar 10% en videre handling.

## Row

**Mål 1. tertial:**

- Vi skal gjøre det enklere for arbeidsgivere å få gjort det de kom for på de åpne sidene som ikke dreier seg om sykmeldt ansatt.
- Vi skal nudge arbeidsgivere til å ta kontakt med NAV om inkludering.

Key results:

- K1: Øke gjennomføringsgraden fra 70% til 73%.
- K2: Øke antall henvendelser om inkludering og forebygging med 3%.

## Row

**Mål 2. tertial:**

- Vi skal gjøre det enklere for arbeidsgivere å få gjort det de kom for på åpne sider som ikke dreier seg om sykmeldt ansatt.
- Vi skal nudge arbeidsgivere til å ta kontakt om inkludering.

Key results:

- K1: Øke gjennomføringsgraden fra 70 til 76 prosent.
- K2: Øke antallet henvendelser om inkludering med 5 prosent via suksesshistorier.

# FAGER

## Row
Mål 2024?

## Row

**Mål 1. tertial:**

- Varsler på epost og SMS til arbeidsgiver kommer frem til arbeidsgiver og arbeidsgiver som holder sin kontaktinformasjon oppdatert
- Arbeidsgivere finner lett møteavtaler med NAV på Min side - arbeidsgiver.
- 90 prosent av arbeidsgiverne får gjort det de skal via Min side - arbeidsgiver.

Key results:

- K1: Antall repeterende kofuvi feil (kontaktinformasjon og fullmakter for virksomheter) for en virksomhet er 0.
- K2: 90% av arbeidsgivere som har en digital møteavtale som vises på Min side går inn på avtalen via lenken.
- K3: Team som bruker funksjonalitet for beskjeder og oppgaver, bruker også sakskonseptet i notifikasjonsplattformen.

## Row

**Mål 2. tertial:** Arbeidsgiver kan enkelt finne og agere på aktuelle saker og møteavtaler de har med NAV på Min side - Arbeidsgiver.

- K1: 90 prosent av arbeidsgiverne får gjort det de skal via Min side - arbeidsgiver. 
- K2: 90% av arbeidsgivere som har en digital møteavtale som vises på Min side går inn på avtalen via lenken.
- K3: To eksisterende produsenter som ikke bruker saksfunksjonalitet i dag tar i bruk dette.

# PIA

## Row

**Mål 2024:** Vi skal gjøre det lettere for NAV-ansatte å kartlegge arbeidsgivers behov, og evaluere den tidsbegrensende og målrettede innsatsen

- K1: Redusere gjennomsnittstid fra virksomheten starter kartlegging til den er gjennomført fra 14 dager til under to dager.
- K2: Av de som har gjennomført en karteggingsprosess med det nye verktøyet hvor saken fullføres, fullfører 70% også evaluering.
- K3: 80% av IA-rådgivere som har brukt løsningen skal oppleve kartlegging som enklere å ta i bruk.
- K4: 70% av IA-rådgivere som har brukt løsningen synes kartleggingsløsningen bidrar til å velge mer treffsikre tiltak.

## Row

**Mål 1. tertial:** IA-rådgivere skal kunne identifisere behov for IA-tjenester på partssamarbeidet i Fia sammen med virksomheter uten avdelinger på en enkel og treffsikker måte.

- K: ?

## Row

**Mål 2. tertial:** IA-rådgivere får tilgang til støtte i Fia til å planlegge samarbeidet med virksomheten ved bruk av kartleggingsresultatet

- K: ?