apiVersion: nais.io/v1
kind: Naisjob
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  labels:
    team: arbeidsgiver-data
  name: arbeidsgiver-datafortelling
  namespace: arbeidsgiver-data
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 8Gi
    requests:
      memory: 1Gi
  ttlSecondsAfterFinished: 340
  schedule: "0 3 * * *"
  backoffLimit: 2
  accessPolicy:
    outbound:
      external:
        - host: {{ nada_host }}
  gcp:
    bigQueryDatasets:
      - name: notifikasjon_platform_dataset
        permission: READ
      - name: pia_til_po_felles_dashboard
        permission: READ
      - name: pia_bigquery_sink_v1_dataset_prod
        permission: READ
  envFrom:
    - secret: arbeidsgiver-nada-secret # value is the secret name in Google Secret Manager
  env:
    - name: NADA_HOST
      value: {{ nada_host }}
    - name: QUARTO_ID
      value: {{ quarto_id }}
